### PR TITLE
Anchorify headings up to h4 level

### PR DESCRIPTION
**Pull request by kaushalmodi**
- Fixes https://github.com/gohugoio/gohugoioTheme/issues/62, https://github.com/gohugoio/hugoDocs/issues/286
- Related https://github.com/gohugoio/hugoDocs/issues/394

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@bep @budparr Should I merge this? Looks like there are no issues with this PR..

**Comment by budparr** [comment]
I haven't run a copy of this. Does this impact the anchors only?

**Comment by kaushalmodi** [comment]
> Does this impact the anchors only?

@bep Sorry about that mess on master branch.. will be more careful next time.

@budparr Here's a test: https://5ab02f530b79b730a16d27d8--gohugoio.netlify.com/content-management/cross-references/#manually-specifying-anchors. *I haven't set the baseURL for this quick test.. so you will need to manually prefix URL's with `https://5ab02f530b79b730a16d27d8--gohugoio.netlify.com/` to see the difference.*

Looks like to anchorifies only the things it should..

**Comment by budparr** [comment]
Looks good to me

**Pull request merged**
