### PR TITLE
Fix problem where non-ASCI menu links cannot be triggered

### PR DESCRIPTION
**Pull request by LinuxSuRen**
see https://github.com/gohugoio/hugo/issues/4654

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@bep Can you help me to review this pr? Thanks a lot.

**Comment by anthonyfok** [comment]
Hi @LinuxSuRen, please fix the commit message as outlined here:

https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines

First of all, the very first word "fix" should be capitalized, i.e. "Fix".

Second, there is some grammar error, e.g. "can not" should be spelt as "cannot" with no space.
The following are some suggested fix (though I admit I am not a native English speaker and thus my English is definitely not perfect either):

* "Fix problem where non-ASCII menu links cannot be triggered"
* "Fix menu rendering so that non-ASCII menu links would work"

**Comment by budparr** [comment]
alternatively, if we used the identifier instead of name, would that solve this issue?

**Comment by anthonyfok** [comment]
Hi @budparr!  Wow, thank you for your instantaneous response!  That was really quick!

The subsequent discussion at Discourse may provide a bit more background, especially where @RickCogley suggested the use of `{{ .Name | safeHTML }}` as a possible solution. 

* https://discourse.gohugo.io/t/menu-cant-be-triggered-when-the-text-is-chinese/11677

Admittedly, @LinuxSuRen wasn't very clear in describing the problem he encountered, and none of us realized he was talking about gohugoioTheme, though in retrospect his stated wish to work on translating Hugo Docs should have been a hint.)

Anyhow, even though the problem was originally with Chinese characters in the menu, I was able to reproduce a non-working menu item by changing "Themes" to "Thèmes":

```diff
--- a/docs/config.toml
+++ b/docs/config.toml
@@ -134,7 +134,7 @@ anchor = "smart"
 
 
 [[menu.docs]]
-  name = "Themes"
+  name = "Thèmes"
   weight = 15
   identifier = "themes"
   post = "break"
```

So hopefully you could reproduce the problem and solve it on your end.

> alternatively, if we used the identifier instead of name, would that solve this issue?

Probably, though I'm sorry I know too little about the front-end to know what is the best solution.
I suppose we could reuse the same identifier for different language translations?  :-)

Thanks again!

**Comment by LinuxSuRen** [comment]
@budparr Indeed, it will be fine if we use identifier instead of name. So, we do not need to use other function.

**Comment by LinuxSuRen** [comment]
@anthonyfok Thanks a lot for your kind tip.
I suggest using the same identifiers for all languages.

**Comment by anthonyfok** [comment]
Hi @LinuxSuRen!  Thank you for fixing the title of your PR (pull request) on GitHub.

But actually, what I meant is your git commit message!  I.e. the message that you type when you run "git commit" where the first letter should be capitalized!  (i.e. "use" → "Use")
@bep is very strict about writing proper git commit messages, and for good reasons.

I needed to squash your two commits into one anyway, so I fixed the git commit message for you this time.

But because you'll likely be making a lot of commits to the Hugo project for the Chinese translation, I wanted to make sure you get this right next time, right off the bat.  ;-)

Last but not least, thank you very much for your contributions!

**Comment by LinuxSuRen** [comment]
First, @anthonyfok thanks a lot for your patient. Be strict is really good, I will take more attention to my English express, and other situation. And I hope I can do more contribution for Hugo.

**Pull request merged**
