### PR TITLE
Improve NAV structure

### PR DESCRIPTION
**Pull request by budparr**
The current structure breaks on phones. I've also tweaked the Hugo image on the home page.

example here: https://gohugotheme-design-tweaks-070618.surge.sh/

### CODE REVIEW

**Comment by bep** [comment]
I know we have not established a commit message guideline for this repo, but it would be good if you could get used to starting your commit messages with a capital letter ("Tweak hero", not "tweak hero".

**Comment by budparr** [comment]
Will do. Thank you.

**Comment by bep** [comment]
>Will do. Thank you.

And then he pulled 3 all lower cased commits into master ...

**Comment by budparr** [comment]
Sorry, I was going to do that in all future commits. Do you want me to revert?

**Comment by bep** [comment]
No, that will just make it even messier.

**Pull request merged**
