### PR TITLE
In "site-footer.html" add class "z-index-10".

### LINKED ISSUE #125: On Mobile in "Use Site Configuration Parameter" section, the tabs come over the navbar
On Mobile in "Use Site Configuration Parameter" section, link: "https://gohugo.io/templates/introduction/", tabs come over the navbar.
I have also attached the screenshot for reference.
hugo

### PR DESCRIPTION
**Pull request by ankitskvmdam**
In "main.css" add class z-index-10 with property z-index: 10.

This fix the issue in which tabs come over the navbar on mobile.

Fixes #125

### CODE REVIEW

**Comment by budparr** [comment]
Hey, @ankitskvmdam Thanks for this. It's a good idea. I just want to point out that we have some z-index classes available already 
```

.z-0 {
    z-index: 0
}

.z-1 {
    z-index: 1
}

.z-2 {
    z-index: 2
}

.z-3 {
    z-index: 3
}

.z-4 {
    z-index: 4
}

.z-5 {
    z-index: 5
}

.z-999 {
    z-index: 999
}

.z-9999 {
    z-index: 9999
}

.z-max {
    z-index: 2147483647
}
```

**Comment by ankitskvmdam** [comment]
I have removed the z-index-10 class and add .z-999 to the div that containing the navbar.

**Comment by bep** [comment]
Hey; I have not been watching this repo for some reason, and these PRs have been sadly neglected. I would love to merge this, but it needs to be rebased against master. I have put this repo back on my watch list.

**Comment by ankitskvmdam** [comment]
I have already signed the agreement.. I don't know why it still shows pending

**Comment by bep** [comment]
>I have already signed the agreement.. I don't know why it still shows pending

Probably a mismatch between email address used in commit and email address used in your GitHub account. Note that you can register more than one email address to fix this.

**Comment by ankitskvmdam** [comment]
Screenshot_20191018-010325
dependabot[bot] didn't signed. How to fix?

**Comment by bep** [comment]
This PR now has 4K commits, which obviously isn't something I can merge.

**Comment by ankitskvmdam** [comment]
So, we have to close this PR?

**Pull request closed without merging**
