### PR TITLE
Add Github Stars button to navigation

### LINKED ISSUE #55: We need a "star on GitHub" button in the top somewhere
Like it or not, Hugo's popularity is measured in GitHub stars (see https://www.staticgen.com/). I would have expected the release announcement of the new docs to increase that star count, but it stayed steady around 25 stars on the day of the announcement.

On the old site, we had a "star on GitHub" button with some Javascript. We should add that back in a visible place, maybe next to the Twitter icon.

This is the GA trend for the GitHub Hugo repo:

image

/cc @spf13 @budparr @digitalcraftsman @rdwatters

### PR DESCRIPTION
**Pull request by budparr**
Fixes #55 

With this PR I've restyled the navigation a bit to accommodate the new GH button.

I've moved the search box to the left, next to the main nav, to make room on the right for the extra button, and styled the search box to be congruent with the nav. 

I've moved the Twitter and GH buttons up and to the right to offset them from the nav.

I'm attaching a screenshot and link to a sample if anyone cares to review.

screen shot 2017-07-21 at 12 41 19 am

https://hugodocs-170720.surge.sh/

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
IMHO the offset between the Twitter / GitHub button and the navbar looks a bit odd. First I thought it was an issue with the layout being scaled through the zoom.

**Comment by budparr** [comment]
It also looks odd when aligned with the nav because of the size differences.

**Comment by budparr** [comment]
I just chose what I felt was the lesser of two evils.

**Comment by bep** [comment]
Yes -- it doesn't look perfect, but it does its job... Let this just stay this for a little bit, we might revisit this and improve (resize the Twitter logo maybe?)

**Comment by budparr** [comment]
I tried to make the Twitter icon as close in size to the GH icon (it's ~ 1px off). The next smallest GH icon was quite small, but we can also just make our own GH icon. I'm just chipping away in small bits and happy to revisit this soon.

**Pull request merged**
