### PR TITLE
Fix render error when lack of tweets

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Fix gohugoio/gohugoioTheme/issues/91

### CODE REVIEW

**Comment by bep** [comment]
This isn't the same as the "other issue". The /data is available to all sites/languages.

**Comment by LinuxSuRen** [comment]
It will get the error, if I don't have the Data.
@bep

**Comment by LinuxSuRen** [comment]
So, what do I need to do?

**Comment by bep** [comment]
Hey; I have not been watching this repo for some reason, and these PRs have been sadly neglected. I would love to merge this, but it needs to be rebased against master. I have put this repo back on my watch list.

**Comment by LinuxSuRen** [comment]
I just did the rebase action. Please feel free to review this PR if it's possible.

**Pull request merged**
